#
# https://github.com/linuxserver/docker-duplicati
# https://www.backblaze.com/blog/duplicati-backups-cloud-storage/
#
--- 
version: '3.7'
services:
#
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=0 #must run as root, should override override anything provided by env
      - PGID=0 #must run as root, should override override anything provided by env
      - TZ=${TZ}
      - DOCKER_MODS=${DOCKER_MODS}
      - CLI_ARGS=${CLI_ARGS}
    volumes:
      - ${LOCVOL1}duplicati:/config
      - ${BACKUPDST}:/backups #backup destination (local), usually /etc/duplicati
      - ${BACKUPSRC1}:/source #backup source 1
      #- ${BACKUPSRC2}:/source2 #backup source 2
      #- ${BACKUPSRC3}:/source3 #backup source 3
      #- ${BACKUPSRC4}:/source3 #backup source 4
#    ports:
#      - 8200:8200 # webUI
    restart: unless-stopped
#
#
networks:
  default:
    name: ${CONNET}
    external: true
