--- 
services:
  headscale:
    image: headscale/headscale:${HEADSCALE_VER} # latest-alpine
    container_name: headscale
    volumes:
      # Please change <CONFIG_PATH> to the fullpath of the config folder just created
      - ${LOCVOL1}headscale/config:/etc/headscale
      - ${LOCVOL1}headscale/data:/var/lib/headscale
    ports:
      - 8081:8080
      - 9091:9090
    restart: unless-stopped
    #command: serve
#
  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:${HEADSCALEUI_VER} # latest
    restart: unless-stopped
    container_name: headscale-ui
    #ports:
    #  - 8443:8443
    #  - 8080:8080
#
#
#
networks:
  default:
    name: ${CONNET}
    external: true
