--- 
version: '3.7'
services:
#
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCVOL1}/nginx:/config
    #ports:
      #- 80:80
      #- 443:443
    restart: unless-stopped
#
  db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${LOCVOL1}/mariadb:/config
    restart: unless-stopped
#
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCVOL1}/heimdall:/config
    restart: unless-stopped
#
  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PMA_ARBITRARY=1 #optional
      - PMA_ABSOLUTE_URI=https://phpmyadmin.finchtech.xyz #optional
    volumes:
      - ${LOCVOL1}/phpmyadmin:/config
    restart: unless-stopped
#
networks:
  default:
    name: ${CONNET}
    external: true
